### PR TITLE
Udoit Issue #7, #14, & #86

### PR DESCRIPTION
**Pull request by techrangerfj**
ColorPicker has already been merged to this branch due to overlap in logic.

### CODE REVIEW

**Comment by bagofarms** [comment]
There is a merge conflict in config/localConfig.template.php.  All of that content has been moved elsewhere, so it should be removed.

Also, please remove jscolor, as it is being included via Bower now.

**Comment by techrangerfj** [comment]
This is also good to go @bagofarms

**Comment by bagofarms** [comment]
Please merge master into this branch and resolve any conflicts.  It's next in line.

**Comment by techrangerfj** [comment]
Good to go @bagofarms

**Comment by bagofarms** [comment]
I'm getting a couple of visual errors with this branch:  https://www.dropbox.com/s/tv5sflo32hdyqh4/Screenshot%202016-02-19%2013.32.34.png?dl=0

https://www.dropbox.com/s/ls739gb6q54b7r8/Screenshot%202016-02-19%2014.15.30.png?dl=0

Please look at Dev and see what's going on.

**Comment by bagofarms** [comment]
Please undo your changes to the reports directory.  I fixed the issue in #112 .

**Comment by bagofarms** [comment]
Issues #7 and #86 seem to be working great!  Unfortunately, issue #14 has a problem.  When i use UFIXIT on one item, it adds "Done!" for all the other occurrences of that error in the page.  Screenshot:  
screenshot 2016-03-10 10 53 12

**Pull request merged**
