### PR TITLE
Resolution for Issue #23

### PR DESCRIPTION
**Pull request by techrangerfj**
Error is now triggered for embedded images that have filename as alt text. Updates #23

### CODE REVIEW

**Comment by bagofarms** [comment]
UDOIT appears to be missing for this error.  I'm not sure if it was ever enabled for this error, but please enable it and i will review this pull request again.

**Comment by techrangerfj** [comment]
You mean UFIXIT?

**Comment by bagofarms** [comment]
Hehe, yep, i meant UFIXIT

**Comment by techrangerfj** [comment]
@bagofarms  Fixes implemented

**Pull request merged**
