### PR TITLE
Issue/47 heroku deployable

### PR DESCRIPTION
**Pull request by iturgeon**
Branch contains breaking changes - will require some config clean up and changes to the web server config.

The majority of changes are in the following groups:

1. Move files around so that everything that doesn't need to be public isn't
2. Split up config to allow Heroku config to be used automatically
3. Change database queries to work on both Postgresql and Mysql so Free heroku hosting is an option
4. Centralize database connection code

Changes:

* organize config into separate parts and adds heroku settings
* centralize database and heroku config update
* add logging to blti failure
* add lots of logging in errors
* add heroku https proxy detection for
* update db connection methods
* new paths for javascript things
* update quail location
* stop including the config everywhere
* better database errors
* move inserted timestamp into bind param to unify mysql/postgress code
* insert query more postgress friendly
* adds  postgress table create to readme

### CODE REVIEW

**Comment by iturgeon** [comment]
This PR references issue #47

**Comment by techrangerfj** [comment]
Testing complete.  Full operational on dev-like environment pending the following changes: 
- Add variables $db_host & $db_port to localConfig.template.php file
- Change value of $db_user_talble form 'user' to 'users' in both localConfig.template.php and heroku.php files

**Comment by iturgeon** [comment]
I added the missing variables and created a new heroku install guide!

**Comment by iturgeon** [comment]
Ok, merged in master and fixed up a bunch of little problems after.

Seems to be working on Heroku, but I'd like to try starting from scratch to make sure the instructions work (and maybe reduce some of the things I added that may not be dependencies - they were based on an example buildpack)

I'd still like to:

* Have heroku build process create the database schema automatically (run migrations?)
* Have the reports write to an external resource (database or s3)

**Comment by iturgeon** [comment]
Heroku build automatically creates the database tables now!  Also, the heroku deploy button works (test it out in the readme)

**Comment by bagofarms** [comment]
Please remove the $error_msg_wrong_referrer and $error_msg_no_referrer messages from settings.php

Also, add a cache-buster for default.js in the udoit template file (https://github.com/iturgeon/UDOIT/blob/issue/47-heroku-deployable/templates/udoit.php#L8)

**Comment by iturgeon** [comment]
Ok, we should be good now!

**Pull request merged**
