### PR TITLE
Resolution for Issue #3

### PR DESCRIPTION
**Pull request by techrangerfj**

### CODE REVIEW

**Comment by techrangerfj** [comment]
This does not quite work as intended yet, will update upon fix

**Comment by techrangerfj** [comment]
This branch is now ready for merging

**Comment by bagofarms** [comment]
Deleting a link worked fine, but changing the text of a link doesn't seem to work on the "click here" i put into this page:  https://webcourses.ucf.edu/courses/1074920/pages/test?module_item_id=8513339

**Comment by techrangerfj** [comment]
@bagofarms did you manage to even get an error for this link in the report you particularly ran? It's not creating an error in the report for me in my test course nor did it create one in the report I ran via the link you provided.

**Comment by bagofarms** [comment]
I got the error to show up in the report.  I also checked the report you ran, and the error is there.  It's the last page under Pages.  It's called "test".

**Comment by techrangerfj** [comment]
@bagofarms ahh I was looking for an error, whilst it actually comes up as an suggestion

**Comment by techrangerfj** [comment]
@bagofarms this pull request is also ready for review

**Pull request merged**
